# https://www.schemastore.org/github-action.json
name: "OpenAI Translate"
description: "OpenAI Translate Action. Translate a text or file to any arbitrary languages."
author: "Shane"

branding:
  icon: "file-text"
  color: "blue"

inputs:
  text:
    description: "Text to Translate"
  file:
    description: "File to Translate"
  languages:
    description: "Languages to Translate Too"
    required: true
  instructions:
    description: "Extra Instructions"
  model:
    description: "Model to Use"
    default: "gpt-4.1-mini"
  token:
    description: "OpenAI API Token"
  summary:
    description: "Add Summary to Job"
    default: "true"

outputs:
  items:
    description: "JSON Mapping"
  results:
    description: "JSON Array"
  input_tokens:
    description: "Total Input Tokens Used"
  output_tokens:
    description: "Total Output Tokens Used"
  total_tokens:
    description: "Total Tokens Used"

runs:
  using: "node24"
  main: "dist/index.js"
